name: kknuntidar_flutter
description: A Flutter port of the KKN Untidar Android app (scaffold)
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  sqflite: ^2.2.8
  path: ^1.8.4
  crypto: ^3.0.2
  convert: ^3.1.1
  shared_preferences: ^2.2.0
  image_picker: ^0.8.7+5
  path_provider: ^2.0.14
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
